# Generated by Django 2.2.6 on 2021-03-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0004_auto_20210302_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Breakfast'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Dinner'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Lunch'),
        ),
    ]
