version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    container_name: postgres
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env

  web:
    build: .
    image: 'praktikumdocker/foodgram:latest'
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - nginx_conf:/code/nginx/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.6
    restart: always
    image: nginx:1.19
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - nginx_conf:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - web
