version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    container_name: postgres
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env

  web:
    build: .
    container_name: foodgram
    image: 'praktikumdocker/foodgram:latest'
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.19
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - ./nginx/default.conf
    ports:
      - 80:80
    depends_on:
      - web
