# Generated by Django 3.1.3 on 2021-03-23 17:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210320_1356'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='recipe_do_not_repeat',
        ),
        migrations.AddConstraint(
            model_name='followuser',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='check_user_is_not_author'),
        ),
    ]
